#!/usr/bin/env node
/**
 * THE SITE IS STATIC, AND STAYS STATIC.
 *
 * On 2026-09-03 this site started paying its whole corpus to render one page. Every route was
 * prerendered, but a time-based `revalidate` turns a prerendered route into an ISR route: the page
 * is regenerated on a request, at runtime, and `loadSnapshotOnce()` reads the entire corpus each
 * time. Over the next fortnight that cost 3.79 billion rows to `site_reader` — 97% of the Empact
 * Supabase organisation's egress, which finished the month at 328% of its allowance with every
 * project days away from being restricted. It was found by the bill.
 *
 * The fix (PR #1, 2026-09-17) is four lines of `export const`. This gate exists because four lines
 * of `export const` are exactly what a later change removes without noticing, and because nothing
 * about the symptom is visible from the site: the pages look right while the meter runs.
 *
 * Two independent checks, because they fail differently:
 *   SOURCE  — every page and every route handler declares itself static, and nothing anywhere
 *             declares a numeric `revalidate`. Runs before the build, so the mistake never ships.
 *   OUTPUT  — every route the build actually emitted has `initialRevalidateSeconds: false`, and
 *             nothing reads the database at request time. Runs after the build, on what was built
 *             rather than on what was written.
 *
 * Run: node scripts/gates/static-only.mjs           (source only, no build needed)
 *      node scripts/gates/static-only.mjs --built   (source + the prerender manifest)
 */
import fs from 'node:fs';
import path from 'node:path';
import { ROOT, fail, pass, walk } from './_util.mjs';

const root = process.env.GATE_ROOT || ROOT;
const checkBuilt = process.argv.includes('--built');
const problems = [];

// The ONE route allowed to be dynamic, and why. It calls revalidateTag and touches no data; a
// fully static page cannot be regenerated by a tag, so it is inert. Anything else added here needs
// an argument for why the corpus is safe from it.
const DYNAMIC_ALLOWED = new Set(['app/api/revalidate/route.ts']);

const rel = (p) => path.relative(root, p).split(path.sep).join('/');

// ---- SOURCE ----------------------------------------------------------------------------------
const routeFiles = [
  ...walk(path.join(root, 'app'), /^page\.tsx?$/),
  ...walk(path.join(root, 'app'), /^route\.ts$/),
  ...walk(path.join(root, 'app'), /^sitemap\.ts$/),
  ...walk(path.join(root, 'app'), /^robots\.ts$/),
];
if (routeFiles.length === 0) fail('static only', 'found no routes under app/ — the gate cannot prove anything');

for (const file of routeFiles) {
  const name = rel(file);
  const src = fs.readFileSync(file, 'utf8');

  // A numeric revalidate is THE defect. `revalidate = 86400` reads as "refresh daily" and means
  // "re-read the corpus on a request".
  const numeric = src.match(/export\s+const\s+revalidate\s*=\s*([0-9][0-9_]*)/);
  if (numeric) problems.push(`${name}: export const revalidate = ${numeric[1]} — a number here is ISR, which is what cost 3.79 billion rows`);

  if (DYNAMIC_ALLOWED.has(name)) continue;

  if (!/export\s+const\s+dynamic\s*=\s*["']force-static["']/.test(src)) {
    problems.push(`${name}: no \`export const dynamic = "force-static"\``);
  }
  // Pages must also pin revalidate to false. A route handler that is force-static does not need it.
  if (/^page\.tsx?$/.test(path.basename(file))
      && !/export\s+const\s+revalidate\s*=\s*false/.test(src)) {
    problems.push(`${name}: no \`export const revalidate = false\``);
  }
  if (/export\s+const\s+dynamic\s*=\s*["']force-dynamic["']/.test(src)) {
    problems.push(`${name}: force-dynamic, and it is not on the allowed list`);
  }
}

// Nothing that runs at request time may reach the corpus loader.
for (const file of walk(path.join(root, 'app', 'api'), /\.tsx?$/)) {
  const src = fs.readFileSync(file, 'utf8');
  if (/getSnapshot|loadSnapshot|from ["']@\/lib\/data\/snapshot["']/.test(src)) {
    problems.push(`${rel(file)}: a request-time route imports the corpus loader — that is the leak, by another door`);
  }
}

// ---- OUTPUT ----------------------------------------------------------------------------------
if (checkBuilt) {
  const manifestPath = path.join(root, '.next', 'prerender-manifest.json');
  if (!fs.existsSync(manifestPath)) {
    fail('static only', 'no .next/prerender-manifest.json — run this after `next build`');
  }
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  const routes = Object.entries(manifest.routes ?? {});
  if (routes.length === 0) fail('static only', 'the build prerendered no routes at all');

  for (const [route, info] of routes) {
    const r = info.initialRevalidateSeconds;
    if (r !== false && r !== undefined) {
      problems.push(`${route}: built with initialRevalidateSeconds = ${r} — this route regenerates at runtime`);
    }
  }
  // A dynamic route that reached the output is the same leak arriving as a lambda.
  const dyn = Object.keys(manifest.dynamicRoutes ?? {});
  const unexpected = dyn.filter((d) => !d.startsWith('/api/'));
  if (unexpected.length) {
    problems.push(`built as dynamic (regenerated per request): ${unexpected.join(', ')}`);
  }
  if (!problems.length) pass('static only (output)', `${routes.length} routes, every one prerendered with no revalidate`);
}

if (problems.length) {
  fail('static only', [
    ...problems,
    '',
    'The site is prerendered from ONE database read at build time. A revalidate, a force-dynamic',
    'page, or a request-time route that loads the snapshot puts the whole corpus back on the',
    'request path. See supabase/migrations/0004 and 0005, and PR #1.',
  ]);
}
pass('static only (source)', `${routeFiles.length} routes declare themselves static`);
